### ISSUE TITLE
Search dialog modal

### ISSUE THREAD

**Issue by sandroguras** [greymass/2nicove#57]
## Inspiration

![Image](https://github.com/user-attachments/assets/461c52c9-0191-408e-8c08-052bd627364d)
![Image](https://github.com/user-attachments/assets/3590d759-a7d5-48c2-960c-e43baceaebc3)

## Functionality
Dynamic text search for accounts, blocks, transactions, etc
Navigation to pages like send, buy ram, etc
???

## Subtasks

- [x] #126
- [x] #127
- [x] #128

**Comment by Goodbyehorses** [comment]
![Search dialog modal draft](https://github.com/user-attachments/assets/44d64860-ebe0-45ca-860e-d196805c34e0)
Here is a draft, i combined some of the different things that was notable in the examples
